### ISSUE TITLE
Add ddd_ruby subreddit

### ISSUE THREAD

**Issue by eterps** [valentjedi/ddd-dynamic#5]
Nice list! Please add my subreddit https://www.reddit.com/r/ddd_ruby/ for Ruby developers interested in Domain-Driven Design. Thanks!

**Comment by valentjedi** [comment]
Added, awesome list, thanks!

**Comment by valentjedi** [comment]
We have some overlaps, but I think it won't hurt.

**Comment by eterps** [comment]
No, that won't hurt in my opinion, the amount of information that can be found on DDD for dynamic languages is quite sparse.

I appreciate your links about Python + DDD, was looking for Python examples recently.

I found this book to be the most helpful for examples that can be easily translated to dynamic languages: https://leanpub.com/ddd-in-php
